# Generated by Django 5.1.5 on 2025-02-05 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_loan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
