# Generated by Django 5.1.5 on 2025-02-05 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_loan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_payments', models.IntegerField(default=0)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='credit.loan')),
            ],
        ),
    ]
