# Generated by Django 5.1.5 on 2025-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_loan_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='num_of_payments',
            field=models.IntegerField(default=0),
        ),
    ]
