# Generated by Django 5.1.5 on 2025-02-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_loan_num_of_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='body',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='percent',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='duration',
            new_name='term',
        ),
    ]
