# Generated by Django 5.1.5 on 2025-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_rename_body_loan_amount_rename_percent_loan_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
