# Generated by Django 5.1.5 on 2025-02-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_loan_payment_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
