# Generated by Django 5.1.5 on 2025-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_loan_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
